spring:
  profiles:
    active: test

---
server:
  port: 5002
spring:
  profiles: dev
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

---
server:
  port: 5003
spring:
  profiles: test
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

